# Generated by Django 2.2 on 2019-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposals',
            new_name='Proposal',
        ),
    ]
