# Generated by Django 2.2 on 2019-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_area_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_name',
            field=models.CharField(default='Here', max_length=20),
        ),
    ]
